### ISSUE TITLE
Consolidate Promise and Future objects?

### ISSUE THREAD

**Issue by younata** [cbguder/CBGPromise#15]
Having very recently explained the difference between Promise and Future, it seems to me that we could save a bit of confusion by just consolidating the Promise and Future classes into the same thing.

Maybe call it a ProTure? 😜

Thoughts?

**Comment by younata** [comment]
A Fumise also works!

**Comment by cbguder** [comment]
Interesting idea, but even if they were the same class, I think we would still want to have separate interfaces to prevent the consumer from resolving the promise, at which point we might as well keep them as separate classes.
